### ISSUE TITLE
Receiving 404 Not Found with existing rule

### ISSUE THREAD

**Issue by svenseeberg** [ananace/ruby-grafana-matrix#6]
In the config.yml there is the following entry:
```
rules:
- name: myrule
  room: "#myroom:matrix.example.com"
  matrix: my-matrix-config
```
Grafana always reports an error. Looking with curl:
```
curl -X POST -d '' http://[xxx:xxxx:xxxx:xxxx::1]:4567/hook?rule=myrule
No such rule configured
```
The server output says
```
xxx:xxxx:xxxx:xxxx::1 - - [21/Feb/2020:13:18:34 CET] "POST /hook?rule=myrule HTTP/1.1" 404 23
- -> /hook?rule=myrule
```

Am I doing something wrong? Its definitely loading the correct config file. Changing the interface works, for example.
