### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by gnupablo** [ananace/ruby-grafana-matrix#8]
Hello, when I try to use the webhook I get the following error.

curl -X POST http://xxx.xxx.xx:9292/hook?rule=hq -d "Content-Length: 0"

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN">
<HTML>
  <HEAD><TITLE>Internal Server Error</TITLE></HEAD>
  <BODY>
    <H1>Internal Server Error</H1>
    wrong number of arguments (given 0, expected 1)
    <HR>
    <ADDRESS>
     WEBrick/1.6.0 (Ruby/2.7.2/2020-10-01) at
     xxx.xxx.xx:9292
    </ADDRESS>
  </BODY>
</HTML>
```
This is the config file, are dummy values:

```
# Set up your HS connections
matrix:
- name: matrix-org
  url: 'https://matrix.org'
  # Create a user - log that user in using a post request
  # curl -XPOST -d '{"type": "m.login.password",
  #                  "user":"grafana",
  #                  "password":"2m4ny53cr3t5"}'
  #      "https://my-matrix-server/_matrix/client/r0/login"
  # Fill that access token in here
  access_token: 'Y2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9uY2F0aW9u'
  #device_id: <device> # Optional
#- name: matrix-priv
#  url: 'https://private.matrix.org'
#  access_token: '<token>'

# The default message type for messages, should be either m.text or m.notice,
# defaults to m.text
msgtype: m.text

# Set up notification ingress rules
rules:
- name: hq               # Name of the rule
  room: "!Y2F0aW9u:matrix.org" # Room or ID
  matrix: matrix-org     # The Matrix HS to use - defaults to first one
  msgtype: m.notice
  # The following values are optional:
  #image: true           # Attach image to the notification?
  #embed_image: true     # Upload and embed the image into the message?
  #templates:
    # Templates to use when rendering the notification, available placeholders:
    #   %TEMPLATES% - lib/grafana_matrix/templates
    #   $<env>      - Environment variables
    #html: "%TEMPLATES%/html.erb" # Path to HTML template
    #plain: "%TEMPLATES%/plain.erb" # Path to plaintext template
  #auth:
    #user: example
    #pass: any HTTP encodable string
#- name: other-hq
#  room: "#hq:private.matrix.org
#  matrix: matrix-priv

# To use the webhook, you need to configure it into Grafana as:
#
# Url: http://<server address>:<port>/hook?rule=<rule name>
# Http Method: POST
```
I am missing something?
